[application]
name = "dioxus-element-plug-docs"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Dioxus Element Plug - Documentation"
base_path = "/dioxus-element-plug"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []
