// Element Plus Icons
//
// 由 SVG 文件自动生成

mod odometer;
mod user;
mod user_filled;
mod lock;
mod key;
mod tickets;
mod menu;
mod list;
mod platform;
mod connection;
mod document;
mod folder;
mod setting;
mod tools;
mod monitor;
mod cloudy;
mod bell;
mod bell_filled;
mod message;
mod search;
mod refresh;
mod delete;
mod delete_filled;
mod edit;
mod edit_pen;
mod check;
mod close;
mod close_bold;
mod plus;
mod arrow_left;
mod arrow_right;
mod arrow_up;
mod arrow_down;
mod arrow_left_bold;
mod arrow_right_bold;
mod arrow_up_bold;
mod arrow_down_bold;
mod more;
mod more_filled;
mod view;
mod hide;
mod upload;
mod upload_filled;
mod download;
mod folder_add;
mod folder_delete;
mod folder_opened;
mod document_add;
mod document_delete;
mod document_copy;
mod document_checked;
mod warning;
mod warning_filled;
mod warn_triangle_filled;
mod info_filled;
mod question_filled;
mod circle_check;
mod circle_check_filled;
mod circle_close;
mod circle_close_filled;
mod circle_plus;
mod circle_plus_filled;
mod success_filled;
mod failed;
mod remove;
mod remove_filled;
mod rank;
mod sort;
mod filter;
mod share;
mod printer;
mod paperclip;
mod link;
mod calendar;
mod clock;
mod timer;
mod notification;
mod message_box;
mod chat_dot_round;
mod chat_line_round;
mod operation;
mod pie_chart;
mod histogram;
mod data_line;
mod data_board;
mod data_analysis;
mod trend_charts;
mod wallet;
mod wallet_filled;
mod money;
mod coin;
mod credit_card;
mod goods;
mod goods_filled;
mod shopping_cart;
mod shopping_cart_full;
mod shop;
mod sell;
mod present;
mod box_icon;
mod office_building;
mod school;
mod location;
mod location_filled;
mod map_location;
mod place;
mod coordinate;
mod full_screen;
mod expand;
mod fold;
mod open;
mod turn_off;
mod unlock;
mod refresh_left;
mod refresh_right;
mod top;
mod bottom;
mod right;
mod top_left;
mod top_right;
mod bottom_left;
mod bottom_right;
mod zoom_in;
mod zoom_out;
mod d_arrow_left;
mod d_arrow_right;
mod caret_left;
mod caret_right;
mod caret_top;
mod caret_bottom;
mod loading;
mod switch;
mod switch_filled;
mod switch_button;
mod star;
mod star_filled;

pub use odometer::Odometer;
pub use user::User;
pub use user_filled::UserFilled;
pub use lock::Lock;
pub use key::Key;
pub use tickets::Tickets;
pub use menu::Menu;
pub use list::List;
pub use platform::Platform;
pub use connection::Connection;
pub use document::Document;
pub use folder::Folder;
pub use setting::Setting;
pub use tools::Tools;
pub use monitor::Monitor;
pub use cloudy::Cloudy;
pub use bell::Bell;
pub use bell_filled::BellFilled;
pub use message::Message;
pub use search::Search;
pub use refresh::Refresh;
pub use delete::Delete;
pub use delete_filled::DeleteFilled;
pub use edit::Edit;
pub use edit_pen::EditPen;
pub use check::Check;
pub use close::Close;
pub use close_bold::CloseBold;
pub use plus::Plus;
pub use arrow_left::ArrowLeft;
pub use arrow_right::ArrowRight;
pub use arrow_up::ArrowUp;
pub use arrow_down::ArrowDown;
pub use arrow_left_bold::ArrowLeftBold;
pub use arrow_right_bold::ArrowRightBold;
pub use arrow_up_bold::ArrowUpBold;
pub use arrow_down_bold::ArrowDownBold;
pub use more::More;
pub use more_filled::MoreFilled;
pub use view::View;
pub use hide::Hide;
pub use upload::Upload;
pub use upload_filled::UploadFilled;
pub use download::Download;
pub use folder_add::FolderAdd;
pub use folder_delete::FolderDelete;
pub use folder_opened::FolderOpened;
pub use document_add::DocumentAdd;
pub use document_delete::DocumentDelete;
pub use document_copy::DocumentCopy;
pub use document_checked::DocumentChecked;
pub use warning::Warning;
pub use warning_filled::WarningFilled;
pub use warn_triangle_filled::WarnTriangleFilled;
pub use info_filled::InfoFilled;
pub use question_filled::QuestionFilled;
pub use circle_check::CircleCheck;
pub use circle_check_filled::CircleCheckFilled;
pub use circle_close::CircleClose;
pub use circle_close_filled::CircleCloseFilled;
pub use circle_plus::CirclePlus;
pub use circle_plus_filled::CirclePlusFilled;
pub use success_filled::SuccessFilled;
pub use failed::Failed;
pub use remove::Remove;
pub use remove_filled::RemoveFilled;
pub use rank::Rank;
pub use sort::Sort;
pub use filter::Filter;
pub use share::Share;
pub use printer::Printer;
pub use paperclip::Paperclip;
pub use link::LinkIcon;
pub use calendar::Calendar;
pub use clock::Clock;
pub use timer::Timer;
pub use notification::Notification;
pub use message_box::MessageBox;
pub use chat_dot_round::ChatDotRound;
pub use chat_line_round::ChatLineRound;
pub use operation::Operation;
pub use pie_chart::PieChart;
pub use histogram::Histogram;
pub use data_line::DataLine;
pub use data_board::DataBoard;
pub use data_analysis::DataAnalysis;
pub use trend_charts::TrendCharts;
pub use wallet::Wallet;
pub use wallet_filled::WalletFilled;
pub use money::Money;
pub use coin::Coin;
pub use credit_card::CreditCard;
pub use goods::Goods;
pub use goods_filled::GoodsFilled;
pub use shopping_cart::ShoppingCart;
pub use shopping_cart_full::ShoppingCartFull;
pub use shop::Shop;
pub use sell::Sell;
pub use present::Present;
pub use box_icon::BoxIcon;
pub use office_building::OfficeBuilding;
pub use school::School;
pub use location::Location;
pub use location_filled::LocationFilled;
pub use map_location::MapLocation;
pub use place::Place;
pub use coordinate::Coordinate;
pub use full_screen::FullScreen;
pub use expand::Expand;
pub use fold::Fold;
pub use open::Open;
pub use turn_off::TurnOff;
pub use unlock::Unlock;
pub use refresh_left::RefreshLeft;
pub use refresh_right::RefreshRight;
pub use top::Top;
pub use bottom::Bottom;
pub use right::Right;
pub use top_left::TopLeft;
pub use top_right::TopRight;
pub use bottom_left::BottomLeft;
pub use bottom_right::BottomRight;
pub use zoom_in::ZoomIn;
pub use zoom_out::ZoomOut;
pub use d_arrow_left::DArrowLeft;
pub use d_arrow_right::DArrowRight;
pub use caret_left::CaretLeft;
pub use caret_right::CaretRight;
pub use caret_top::CaretTop;
pub use caret_bottom::CaretBottom;
pub use loading::Loading;
pub use switch::Switch;
pub use switch_filled::SwitchFilled;
pub use switch_button::SwitchButton;
pub use star::Star;
pub use star_filled::StarFilled;
