[application]
name = "modern-pure-rust-example"
bin_package_name = "modern-pure-rust-example"

[web.app]
base_path = "/"

[web.watcher]
index_on_404 = true

debounce_interval = "250ms"

tool = { command = "tailwindcss", build_args = ["-i", "./input.css", "-o", "./assets/tailwind.css"], watch_args = ["-i", "./input.css", "-o", "./assets/tailwind.css", "--watch"] }

[web.resource]
style = ["assets/tailwind.css"]
script = []

[web.resource.dev]
style = []
script = []